name: CI/CD Frontend

#on:
#  pull_request:
#    branches:
#      - release
#    types:
#      - closed
#    paths-ignore:
#      - pubspec.yaml

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        working-directory: codigo-fonte/frontend/marcos-turismo
        run: npm ci
     
      - name: Build Angular app
        working-directory: codigo-fonte/frontend/marcos-turismo
        run: ng build --configuration=production
   
      - name: Rename CSR index file to index.html
        run: mv codigo-fonte/frontend/marcos-turismo/dist/marcos-turismo/browser/index.csr.html codigo-fonte/frontend/marcos-turismo/dist/marcos-turismo/browser/index.html

      - name: Upload build files manually via SCP
        run: |
          cd codigo-fonte/frontend/marcos-turismo/dist/marcos-turismo/browser
          scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no * ${{ secrets.HOST_SSH_USER }}@${{ secrets.HOST_SSH_IP }}:${{ secrets.HOST_DEPLOY_DIR }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.HOST_SSH_KEY }}

      - name: Reload Apache
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST_SSH_IP }}
          username: ${{ secrets.HOST_SSH_USER }}
          key: ${{ secrets.HOST_SSH_KEY }}
          script: |
            sudo systemctl reload apache2 || echo "Apache not reloaded"